<a href="https://colab.research.google.com/github/JuneSHYoo/AI_DeepLearning/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 1 
Answer folloing questions using tensorflow's gradient tape.  

EX)
```
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
```

### Q1 Differentiate $y = x^2 + 3x + 1$ with respect to a scalar variable $x$.

In [1]:
import tensorflow as tf
import numpy

In [2]:
x = tf.Variable(0.)
with tf.GradientTape() as tape:
  y = x**2 + 3*x + 1
dy_dx = tape.gradient(y,x)

In [3]:
dy_dx.numpy()

3.0

### Q2 Differentiate $y = X^3 + 3X + 5$ with respect to a 2 by 2 matrix variable $X$.

In [4]:
X = tf.Variable(tf.random.uniform([2,2]))
with tf.GradientTape() as tape:
  y = X**3 + 3*X + 5
dy_dX = tape.gradient(y,X)

In [5]:
dy_dX

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4.0763164, 3.3403814],
       [3.324098 , 3.087906 ]], dtype=float32)>

In [6]:
print('shape of X :', X.shape)
print('shape of dy_dX :', dy_dX.shape)

shape of X : (2, 2)
shape of dy_dX : (2, 2)


### Q3 Differentiate $z = X^3 y^2 + 3X + 2xy + 1$ with respect to a 2 by 2 matrix variable $X$ and a scalar variable $y$.

In [7]:
y = tf.Variable(1.)
X = tf.Variable(tf.random.uniform([2,2]))
with tf.GradientTape() as tape:
  z = X**3 * y**2 + 3*X + 2*X*y + 1
dz_dX_and_dy = tape.gradient(z ,[X,y])

In [16]:
# result
print("dz_dX :" ,dz_dX_and_dy[0])
print("dz_dy :" ,dz_dX_and_dy[1].numpy())

dz_dX : tf.Tensor(
[[5.228007  5.01523  ]
 [5.0917144 5.9727845]], shape=(2, 2), dtype=float32)
dz_dy : 2.60506
