<a href="https://colab.research.google.com/github/JuneSHYoo/AI_DeepLearning/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 1 
Answer folloing questions using tensorflow's gradient tape.  

EX)
```
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
```

### Q1 Differentiate $y = x^2 + 3x + 1$ with respect to a scalar variable $x$.

In [28]:
import tensorflow as tf
import numpy

In [44]:
x = tf.Variable(0.)
with tf.GradientTape() as tape:
  y = x**2 + 3*x + 1
dy_dx = tape.gradient(y,x)

In [46]:
dy_dx.numpy()

3.0

### Q2 Differentiate $y = X^3 + 3X + 5$ with respect to a 2 by 2 matrix variable $X$.

In [38]:
X = tf.Variable(tf.random.uniform([2,2]))
with tf.GradientTape() as tape:
  y = X**3 + 3*X + 5
dy_dX = tape.gradient(y,X)

In [43]:
dy_dX

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4.621337 , 5.4878387],
       [3.386354 , 5.814765 ]], dtype=float32)>

In [48]:
print('shape of X :', X.shape)
print('shape of dy_dX :', dy_dX.shape)

shape of X : (2, 2)
shape of dy_dX : (2, 2)


### Q3 Differentiate $z = X^3 y^2 + 3X + 2xy + 1$ with respect to a 2 by 2 matrix variable $X$ and a scalar variable $y$.

In [51]:
y = tf.Variable(1.)
X = tf.Variable(tf.random.uniform([2,2]))
with tf.GradientTape() as tape:
  z = X**3 * y**2 + 3*X + 2*X*y + 1
dz_dX_and_dy = tape.gradient(z ,[X,y])

In [52]:
dz_dX_and_dy

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[7.242101 , 6.835408 ],
        [6.6884866, 6.4339075]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.931171>]